#!/usr/bin/perl

$tmp = ".arlibtmp";

print `rm -rf $tmp; mkdir $tmp`;
(-d $tmp) or die ("Could not create temporary directory $tmp\n");

$first = 1;
while(scalar @ARGV)
{
	$_ = shift @ARGV;
	if(/.*\.a/)
	{
		if($first) {
			push @ar, "../$_";	## modify path to destination library

			$first = 0;
			next;
		}
		print `(cd $tmp; ar x ../$_)`;
	}
	else
	{
		if($first)	## still eating parameters
		{
			push @ar, $_;
		} else {
			push @ar, "../$_";
		}
	}
}

@objs = `ls -1 $tmp`;
foreach(@objs) { chomp($_); }
push @ar, @objs;

$cmdline = "(cd $tmp && ar " . join(' ', @ar) . ")";
print `$cmdline`;

#print "$cmdline\n";

print `rm -rf $tmp`;
